### PR TITLE
Update guppy.nf

### PR DESCRIPTION
**Pull request by replikation**
* reverting --trim, loses lots of reads. trimm option seems also to be not activated in artic

### CODE REVIEW

**Comment by replikation** [comment]
@hoelzer please compare the "edge case" fast5 with master and this branch. found evidence of clean "barcode trimming" not sure if artic is also removing these regions "again" therefore causing issues with the genome construction

**Comment by replikation** [comment]
@RaverJay maybe you have also a good fast5 testdata set to check master results versus this branch. (we expect to lose lots of reads in master with guppy trim option on)

**Comment by RaverJay** [comment]
What are the results with the test_fast5 profile data?

**Comment by hoelzer** [comment]
> 
> 
> Will do some runs.
> 
> Random thoughts:
> 
>     * should a guppy_cpu option be added?
> 
>     * renaming  --dir  to --fast5  would be much clearer imho

Imho we have guppy CPU support already

`--fast5` instead of `--dir` true, would be more descriptive

**Comment by RaverJay** [comment]
> Imho we have guppy CPU support already

dunno, just started on a machine without a GPU and the guppy command just died

**Comment by hoelzer** [comment]
> 
> 
> > Imho we have guppy CPU support already
> 
> dunno, just started on a machine without a GPU and the guppy command just died

https://github.com/replikation/poreCov/blob/master/poreCov.nf#L292

I had no GPU access when I started at RKI so I requested that ;)

**Comment by RaverJay** [comment]
Could also just use the same container, detect the (non-)presence of a GPU during runtime and run Guppy in the fitting mode

**Comment by hoelzer** [comment]
> 
> 
> Could also just use the same container, detect the (non-)presence of a GPU during runtime and run Guppy in the fitting mode
> EDIT: Because afaik guppy_gpu can always also run in cpu mode

Ahh okay. There was a reason we used two different containers for GPU and CPU Guppy - but I can't remember why :) So sure, if we can use the same GPU container to also provide CPU basecalling (and in best case detected on the fly) this would make things way easier for users w/o GPU access (and loads of time).

**Comment by replikation** [comment]
I think the gpu Container fails with lib cuda error if you start it without a underlying gpu

**Comment by replikation** [comment]
€ seems to work now with the guppy:gpu container. so we could build in a autoswitch. (if guppy gpu fails use cpu in stead

**Comment by hoelzer** [comment]
> 
> 
> € seems to work now with the guppy:gpu container. so we could build in a autoswitch. (if guppy gpu fails use cpu in stead

cool! then we also maintain only one container, good

**Comment by hoelzer** [comment]
So guys, regarding the trimming issue I experienced with our V3 400bp amplicon data. To summarize:

* v0.6.1 --> all looks good
* then I run from some master branch where you activated barcode trimming in guppy --> I got very short reads and loads of NNNNN in the consensuses
* then I run on the `trimm_test` branch --> all looks good again

So for me, changing back to non-trimming via guppy solved that issue

**Comment by replikation** [comment]
* okay i merge this back in. crazy stuff. thx @hoelzer 
* also strange that the 1200 amplicons are fine with it...

**Comment by hoelzer** [comment]
Really weired. But bc/ of that we should always test 400 and 1200 bp amplicon sets to be sure changes work for both kinds

thx!

**Comment by replikation** [comment]
yeah iwas thinking about writing a bigger test script with data on e.g. osf to run which tests all the flags and options at once maybe. for releases.

**Comment by hoelzer** [comment]
test are always great (y)

**Pull request merged**
