### PR TITLE
Nextclade docker update

### PR DESCRIPTION
**Pull request by replikation**
* included now nextclade for `--update`
* nextclade containers are build every week
* they contain nextclade version and the date of the data (like pangolin)
* this information is also noted in the final report (version + data)

* @hoelzer can you please test this build via singularity using the `--update flag` ?

### CODE REVIEW

**Comment by replikation** [comment]
* set the default basecaller and medaka model to "hac". Using "sup" is up to the user

**Comment by hoelzer** [comment]
@replikation looks basically good and runs also in our restricted environment w/ Singularity. But I noticed some difference regarding deletions in Delta sequences. Basically, w/ v0.10.3 we always see the deletion 

S:F157-, S:R158-

but with the current `nextclade_docker_update` branch we always see

S:E156-, S:F157-

So shifted by one position. The other SNPs seem fine. Another Delta-characteristic deletion at position 

ORF8:D119-, ORF8:F120-

ist not touched... so stays same between the two versions. 

Any idea where this difference could come from? 0_0

v0.10.3
image

This branch
image

**Comment by hoelzer** [comment]
One second... you extract the information about insertions and deletions from the Nextclade output, right? Then there might be a difference between the quite old and new nextclade version and that causes the difference. Actually, the new positions might be even more accurate

**Comment by hoelzer** [comment]
yep, the consensus sequences are exactly the same (same md5sum) but Nextclade versions annotate this specific deletion position differently. Hach, Friday edge case discovered :leichtes_lächeln: but that's fine I would say. Likely even more accurate then the old Nextclade information

**Review by hoelzer — APPROVED** [review]
So looks good. I checked and all the consensus sequences are same between the latest release version and this branch. And having the newer Nextclade INDEL position information makes anyway sense.

**Comment by replikation** [comment]
ah yes nexclade is new they adjusted some things. the nextclade version and database version is now also noted on the final report to avoid "differences" between databases. Thank you ill do some testing merge and prep a release

**Pull request merged**
