### PR TITLE
Covarplot & Reference BAM output

### PR DESCRIPTION
**Pull request by hoelzer**
## CoVarPlot amplicon coverage
* added https://github.com/Psy-Fer/CoVarPlot
* tested w/ `medaka`, untested w/ `nanopolish` but added the code as well
* solves https://github.com/replikation/poreCov/issues/99

Example output:

image

## BAM 
* for further investigations it would be nice to primer clipped BAM output where reads are mapped to the reference genome  (to actually check deletions, ...) 
    * I simply publish now a `SAMPLENAME_mapped_MN908947.3.primertrimmed.sorted.bam` file from the ARTIC output where the reads are mapped to the reference and also primer clipped (the BAM is used for variant calling then)
* I would even vote to not publish the BAM where (non-primer clipped!) reads are mapped to the reconstructed consensus just for coverage plotting
    * such a BAM might cause confusion bc/ primers are not clipped (at least I think that's the case) and also just shows the mapping to the consensus
    *  fine for the coverage plot, although it would be even better to get rid of the primers for more accurate coverage plotting
    
I did not change the code, but I vote for not publishing the "coverage BAM". What do you think? We could then just comment this out in this PR. Or do you use the coverage BAM in any way?

### CODE REVIEW

**Review by replikation — APPROVED** [review]
* looks good on my end, doing some testing now

**Comment by replikation** [comment]
@hoelzer are we using this as a drop-in replacement for the old coverage plots in the genome dir? (the red ones, not the ones for the final report) - if so I think we should remove the old plots (this: https://github.com/replikation/poreCov/blob/master/workflows/process/coverage_plot.nf)

**Comment by hoelzer** [comment]
@replikation good question. I think to avoid confusion we are better with removing the old per-sample coverage plots. Also, they are based on the reads mapped to the consensus and not the reads mapped to the reference. And I think such kind of amplicon-focused coverage plots make anyway more sense. 

By that, we could remove 

* the old per-sample coverage plots
* the output of the reads-mapped-to-consensus BAM

Then the user only gets in the Genome folder per sample:

* coverage plot focused on amplicons (and based on mapping to the reference)
* BAM w/ primer-clipped reads mapped to the reference to investigate genotype frequencies, deletions, drops, ...

**Comment by hoelzer** [comment]
@replikation so from my side this PR is ready:

* removed the per-sample coverage plots (also the BWA mapping that was done to get these plots)
* output now a) CoVarPlot amplicon coverage plots and b) BAM (+index) for the primer-clipped reads mapped to the Wuhan reference (to investigate how the consensus was reconstructed, if needed)

We could discuss the nameing:

* `SAMPLENAME_amplicon_coverage.png`
* `SAMPLENAME_mapped_MN908947.3.primertrimmed.sorted.bam`

but I thought being explicit here is better than vague.

**Comment by hoelzer** [comment]
the developer of CoVarPlot said he will add some more features in the near future so we can update these plots a bit (colors, PDF output, ...) but for now it's working.

**Comment by replikation** [comment]
perfect thanks. 
ill merge after some test

**Review by replikation — APPROVED** [review]

**Comment by replikation** [comment]
@hoelzer to bad that the y axis is "linear" maxes inspections at around 20x coverage difficult. ill merge

**Comment by hoelzer** [comment]
@replikation thx!

> @hoelzer to bad that the y axis is "linear" makes inspections at around 20x coverage difficult. ill merge

That's true, maybe something we can request from the developer. I will write an issue :)

**Pull request merged**
