### PR TITLE
Use nextclade aa insertions

### PR DESCRIPTION
**Pull request by RaverJay**
Implements #189 

- removed my custom solution
- bumped version of pangolin/nextclade containers, but:
- no new nextclade release yet, so will not work even with --update
- should work when it is released, and will add a new version bump

### CODE REVIEW

**Comment by RaverJay** [comment]
@replikation please build a nextclade 1.10 container :)

**Comment by RaverJay** [comment]
Thinking of adding the frameshift column to this PR (#199)

With a big red warning if any frameshifts were found:
image

**Comment by hoelzer** [comment]
@RaverJay I like this disclaimer alert message. I would maybe write "This error can cause masking of downstream ..."

Because tools such as pangolin, covSonar, ... can actually deal w/ most frameshifts and still correctly call the downstream changes. Thats also why were still able to assign Omicron BA.1 w/ high confidence via pangolin although the report only showed one amino acid change in spike based on the Nextstrain output. :) 

I wonder if we should simply report Frameshifts on nucleotide level and not only spike? Otherwise, the alert message is shown but then no sequence is obviously marked as having a frameshift. E.g. lets say the frameshift is in the ORF1a or so?

**Comment by RaverJay** [comment]
Data shown is not limited to spike only, if others were there they would be shown (the brackets only explain that purple means spike)

Nextclade gives frameshifts only on AA level

**Comment by hoelzer** [comment]
> Data shown is not limited to spike only, if others were there they would be shown (the brackets only explain that purple means spike)
> 
> Nextclade gives frameshifts only on AA level

Ah true, the Spike ones are just highlighted you're right. 

ad Nextclade FS only on AA lvl: ah k, then it's like that

**Review by replikation — APPROVED** [review]

**Comment by RaverJay** [comment]
Mistake on my part, I forgot to push the latest changes (warning message and frameshift column) to the branch, so its not included in the merge I think

**Pull request merged**
