### PR TITLE
Parameter optimization

### PR DESCRIPTION
**Pull request by replikation**
* @iferres @hoelzer  for modifying parameters and testing
* otherwise i use the most recent artic release implementation
* i increase the normalization maybe the additional information already helps

* should also look into the filtering of reads. might be better to use `artic guppyplex --directory ` with additional quality filtering (see https://artic.readthedocs.io/en/latest/commands/)

### CODE REVIEW

**Comment by iferres** [comment]
Ok, we will launch a job with this branch version and will report back when is done. I asked Natalia, my colleague to open a new issue describing what she is seeing. I've just talked with her (we are working remotely as we are having a surge in covid cases), and what she describes doesn't look to be related to this parameter.

**Comment by replikation** [comment]
@iferres might be something related to the demultiplexing and read filtering step i assume.  ill test this out the moment I got your fastq file. I ping you in this PR if i think i got i fixed. thanks again

**Comment by iferres** [comment]
Hey, so the "issue" (not a bug, a feature actually) was resolved, and parameters were completely unrelated to that. Feel free to close this branch if you want. And thanks a lot for your quick response and willingness to approach my requests! Very cool lab by the way. The one where [I work at](https://iraola-lab.com/about/) has very similar interests, may be we could collaborate in the future. Bests!

**Comment by replikation** [comment]
@iferres thanks for the reply, i added you also through twitter/researchgate so we can talk if some interesting cooperation com up :)
* i keep this branch open as i want to test some more stringent demultiplexing approaches here

**Pull request merged**
