### PR TITLE
Add guppy/medaka models, print out 'Description' column

### LINKED ISSUE #136: Optional "description" column in report TSV/Excel
This might be a kinda specific request but maybe it's of general use and easy to add:

We would like to add another column w/ IDs to the final report files (mainly the Excel) because this is needed for reporting. Of course, this can be done w/ some script that runs after poreCov to update the TSV/Excel file. However, it might be interesting to extend the samplesheet input by another optional column (e.g. `description`) that, if available, is added as an additional column to the TSV/Excel. 

e.g.:

```
_id,Status,Description
IMSS-00157,barcode01,fancy-sample
``` 

and in the report then

```
IMSS-00157    fancy-sample    89%N    B.1.1.7    etc...
```

What do you think? We can also add this on our site outside of the poreCov functionality if you dont see the general use. Such a description column would also allow to still have the barcode information in the output, if needed, by defnining as the samplesheet input

```
_id,Status,Description
IMSS-00157,barcode01,barcode01
```

### PR DESCRIPTION
**Pull request by RaverJay**
Fixes #136
(and half of #142)

Report now includes:
- Guppy model if basecalling from fast5
- Medaka model if ARTIC is run (just realised that this is misleading/wrong if using nanopolish)
- If providing a samples.csv: If a column is named exactly 'Description', it is added to the output tables (this could be extended to others, or allow selection of the columns via parameters)

image

### CODE REVIEW

**Comment by replikation** [comment]
nice work, ill keep this open because we need the same for nextclade, and there is currently an "auto build" (similar to pangolin) in the works (nearly done).   it will be also `nanozoo/nextclade:nextcladeversion--databaseversion`

**Comment by hoelzer** [comment]
Awesome, thx @RaverJay ! The "Description" col in the samplesheet is helpful - likely worth mentioning this feature also in the readme?

**Comment by hoelzer** [comment]
Here: https://github.com/replikation/poreCov#sample-sheet

**Comment by RaverJay** [comment]
> Awesome, thx @RaverJay ! The "Description" col in the samplesheet is helpful - likely worth mentioning this feature also in the readme?

Done

**Comment by hoelzer** [comment]
> > Awesome, thx @RaverJay ! The "Description" col in the samplesheet is helpful - likely worth mentioning this feature also in the readme?
> 
> Done

Superb 👍

**Review by replikation — APPROVED** [review]

**Comment by replikation** [comment]
@RaverJay great work

**Review by replikation — APPROVED** [review]

**Pull request merged**
