### PR TITLE
Freyja integration

### PR DESCRIPTION
**Pull request by DataSpott**
Integration of Freyja for metagenomic screening of reads.
Includes also a restructuring of the LCS-tool for metagenomic read-analysis.

### CODE REVIEW

**Comment by hoelzer** [comment]
@DataSpott okay, I pushed my changes to make the `update` for freyja happen in the work dir to also work with Singularity. 

Please have a look, I also hope I set all the params correctly so it **really** uses the downloaded files in the workdir and does not fallback to the old files installed in the freyja conda env

**Review by replikation — CHANGES_REQUESTED** [review]
please update stub otherwise okay

**Comment by hoelzer** [comment]
> please update stub otherwise okay

Can @DataSpott do that? Would be nice if we can merge this then and then we would also test further

**Comment by DataSpott** [comment]
Had already a look at it, but could not yet identify the reason why stub fails. Happens in the fast5-test but what I saw so far the stub-profiles are setup correctly. Need to investigate this further.

**Comment by DataSpott** [comment]
Found the error. Will now conduct a test run to make sure that everything works properly and report than if the merge can be done.

**Review by replikation — APPROVED** [review]

**Comment by replikation** [comment]
can be merged if everything is also fine on your end @hoelzer

**Comment by DataSpott** [comment]
Just to follow up: my "test_fast5"-profile run was successful with the latest changes.

**Comment by hoelzer** [comment]
Also fine for me!

After the merge we should still keep an eye on any results bc as we discussed on BC I am not 100% certain the update parameter works as intended. I am 95% sure :)

We can test this with a very recent patient sample that has a very fresh lineage assignment (a lineage not assigned on March) and then see what the pipeline annotates with frejya in default mode and with update. As a sanity check

**Pull request merged**
