### PR TITLE
Feature add af to vc fs

### PR DESCRIPTION
**Pull request by MarieLataretu**
- outputs an additional VCF with the alternate allele ratios (`AF`) for all passed and failed variants
- only for ARTIC w/ medaka and fast5 or fastq intput
- adds a column to the datatable (tsv and excel) containing the number of mixed sites of the sample
    - definition of a mixed site: `INFO/DP>${params.min_depth} & INFO/AF>=0.3 & INFO/AF<=0.8`

Relates to/fixes (?) #266 

All three test profiles run successfully: 
```
nextflow run poreCov.nf -profile test_fast5,slurm,singularity --cachedir [...] -resume --update
nextflow run poreCov.nf -profile test_fastq,slurm,singularity --cachedir [...] -resume --update
nextflow run poreCov.nf -profile test_fasta,slurm,singularity --cachedir [...] -resume --update
```

### CODE REVIEW

**Comment by hoelzer** [comment]
oh wow - so it is actually possible to get allele frequencies (AF) from medaka? This would be really nice to have... thx

**Comment by MarieLataretu** [comment]
It's "stolen" form Galaxy 😅 [MIT license, so all good]

After ARTIC they do the following:
`medaka tools annotate --dpsp --pad 25` and then a custom python script that does things and adds a `AF` INFO field

I can't say how it compares to other tools, but it's seems to be somewhat in line with what one would see in IGV.

**Comment by hoelzer** [comment]
Nice!

**Review by replikation — APPROVED** [review]
we do some quick test runs and merge when fine. thank you :)

**Comment by replikation** [comment]
works on our end

**Pull request merged**
