### PR TITLE
bump default container version for pangolin and nextclade

### PR DESCRIPTION
**Pull request by MarieLataretu**
bump to latest containers:
- nanozoo/pangolin-v4:4.3--1.25.1
- nanozoo/nextclade3:3.2.1--2024-02-16

### CODE REVIEW

**Comment by replikation** [comment]
Could you also adjust this part and test on --update?

https://github.com/replikation/poreCov/blob/0ff536fe01c2c2410e1b666c74a3bd43bd8dc287/poreCov.nf#L260

**Comment by replikation** [comment]
@DataSpott can you validate the PR?

**Comment by replikation** [comment]
thank you @MarieLataretu

**Comment by DataSpott** [comment]
Tested 44 samples with and without [--update]-flag. Both runs were completed successfully. Also, with the update flag, the first attempt to create the final report-HTML failed, but completed on the 2nd try using [-resume].

**Pull request merged**
