### PR TITLE
Update guppy GPU and CPU version

### PR DESCRIPTION
**Pull request by hoelzer**
needs proper testing before merge!

### CODE REVIEW

**Comment by replikation** [comment]
+ some changes between medaka model and guppy? I am not aware of any

**Comment by hoelzer** [comment]
I am also not aware of any changes. I will do some runs w/ the current
Release and this branch to compare next week

Christian Brandt ***@***.***> schrieb am So., 25. Apr. 2021,
14:27:

**Comment by hoelzer** [comment]
I experienced issues w/ this new guppy version due to a restructured output folder structure from the guppy basecalling

**Comment by replikation** [comment]
we have currently cuda errors for this version

**Comment by replikation** [comment]
* but you can close this one and continue on #105

**Pull request closed without merging**
