### PR TITLE
Add all samples from samples.csv to report table

### LINKED ISSUE #92: samples from samplesheet.yml are not reported
This might be an issue with an older version (analyses was run end of February). 

Samples that are given in the samplesheet.yml and yield no reads in demultiplexing are not reported in output. this may lead to missing information in tracking samples further downstream. 

could you add the information of lacking reads in a report.csv or similar?

### PR DESCRIPTION
**Pull request by RaverJay**
- adds missing samples to report table and datatables (fixes #92)
- forgot to make a new branch :<

image

### CODE REVIEW

**Comment by hoelzer** [comment]
great, thanks @RaverJay ! Would be nice to have this soonish in a release if everything works. I can also do a test run with a run where I know that one sample has to few reads after basecalling

**Comment by RaverJay** [comment]
Yeah better test it some more, I only did 3 runs so far (one without --samples, one with all samples there, one with a sample missing)

**Review by replikation — APPROVED** [review]

**Comment by hoelzer** [comment]
Ah, can you confirm @replikation ? I thought that we have (had) a filter that checks for FASTQs after basecalling that only have a handfull of reads and removes them. Because you always get some mis-classifications ofter demultiplexing that you dont want to continue processing in the pipeline.

**Comment by hoelzer** [comment]
Ah great! Thx

Christian Brandt ***@***.***> schrieb am Di., 30. März 2021,
19:28:

**Pull request merged**
