### PR TITLE
rki output and some smaller fixes

### PR DESCRIPTION
**Pull request by replikation**
* rki style output branch

Missing:

* [x] pangolin lineage in rki csv
* [x] collect fastas into multifasta for rki

### CODE REVIEW

**Comment by replikation** [comment]
@hoelzer apparently rki does not have a "pangolin" field... so I skip adding this

**Comment by hoelzer** [comment]
> @hoelzer apparently rki does not have a "pangolin" field... so I skip adding this

@replikation what do you mean by "does not have a pangolin" field? The current DESH upload portal? No, currently there is no field to put the pangolin lineage.

**Comment by replikation** [comment]
@hoelzer yep DESH upload.

**Comment by hoelzer** [comment]
> @hoelzer yep DESH upload.

Yeah, this is the first very very basic form for the first days (phase 0, https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/DESH/DESH.html) and will be subject to change. So we just need to adjust the output format following changes to the upload portal in the next days/weeks

**Comment by replikation** [comment]
yep we need to do this either way as we are sequencing every week now

**Comment by replikation** [comment]
* @hoelzer cleaned up output structure and added a combined fasta for the `--rki` flag
* html output not in here ill do a separate PR for this

**Comment by replikation** [comment]
* coul improve the "fastq collection" via `find` for the barcode dirs. then it would be "more" recursive stable...?

**Comment by replikation** [comment]
*PR closes #26 #27 #19

**Comment by hoelzer** [comment]
```
taxon,lineage,probability,pangoLEARN_version,status,note
FAO96286_barcode07,B.1.177,1.0,2021-01-11,passed_qc,
```

@replikation the column headers are not correct, or? First column is the `sample` or `FASTA ID` and not the `taxon`? Or is this just default pangolin output style (then let's keep it)

**Review by hoelzer — APPROVED** [review]

**Comment by replikation** [comment]
+ @hoelzer oh good find, this is from my "collect all pangolin report part" [here](https://github.com/replikation/poreCov/blob/29e0d4abb9c087449381147c47bdec43489556a6/workflows/determine_lineage.nf#L13), so it can be manually changed

**Comment by hoelzer** [comment]
@replikation fine on my side! Nothing burned down :D checked on laptop and cluster and also with the new `--fastq_raw` option. 

The comment above regarding lineage output is just minor

**Pull request merged**
