### PR TITLE
Add Scorpio + constellations column and versions

### PR DESCRIPTION
**Pull request by RaverJay**
- implements #173
- will add a Scorpio column to the report if any samples had a scorpio call, omitted otherwise
- Scorpio and constellations version is determined by spinning up the pangolin container once

Bonus:
- adds gzip input capabilities for --fasta (e.g. blabla.fasta.gz)
- bumps up default version of Pangolin and Nextclade to new ones

Needs testing

### CODE REVIEW

**Comment by hoelzer** [comment]
great thx @RaverJay !

Just did a test run (that has no Omicron included). But no scorpio information added to the report? I suggest to simply add another row after the pangolin version 

image

**Comment by hoelzer** [comment]
I will also da test w/ public omicron raw data now

**Comment by RaverJay** [comment]
Yeah the logic was flipped for testing, fixed now - please pull the latest commit

Thanks for testing!

**Comment by RaverJay** [comment]
image

**Comment by RaverJay** [comment]
Maybe we should add a warning if the Pangolin / Nextclade version is very old, because I had this is my first test, obviously the PangoLEARN from July is pretty much useless now

**Comment by hoelzer** [comment]
Great, looks good now also here! And such a warning would be great if you can easily add it. Bc/ yeah, if someone fails to run the `--update` command the lineage assingments can be really odd

**Comment by RaverJay** [comment]
How about this:
image

And keep the PangoLEARN version also in this top part. Could do the same for NextClade?

**Comment by hoelzer** [comment]
@RaverJay ! great, having this in the report is even better than in terminal. Yeah, would be also nice for Nextclade then if you can easily add that

**Comment by hoelzer** [comment]
So looks good I'd say, also just did another regular run again with the current PR version:

image

**Comment by RaverJay** [comment]
image
Nextclade data version is in

**Comment by hoelzer** [comment]
@RaverJay can this be merged from your side? I also just run a test, looks all good!

**Comment by RaverJay** [comment]
Well it works for me, but I never trust changes until Chris has run some cloud tests :D

**Comment by hoelzer** [comment]
;) I agreed w/ him that we merge smaller changes and do prerelases, he will then later also test and then we do a major release

**Pull request merged**
