### PR TITLE
Summary report

### PR DESCRIPTION
**Pull request by RaverJay**
Add a summary report (html) that combines output in an easy to read table overview for all samples.

Further ideas:
- add tool version numbers
- link krona plots

NOTE: changed krona output html name (added '_krona') for better descriptiveness of the filename

### CODE REVIEW

**Comment by RaverJay** [comment]
added Ns, tool versions
more ideas:
- print all tool versions
- print poreCov params
- mark spike mutations (colors?)

**Comment by replikation** [comment]
+1 for marking spike proteins.
* params could be a long list to add but might be useful
* poreCov version might be useful (`workflow.revision`)
* all tool versions could be annoying.
* what happens If a user provides "fasta" only? is the kraken2 column just "removed"? 
   * (we have fast5, fastq, and fasta as input) so user can drop fastas constructed by other technologies

**Comment by RaverJay** [comment]
image

running todos:
- implement fasta input cleaning (report will already work for clean files, omitting kraken column)
- add only most important poreCov params and tool versions (input type, primer version, ARTIC etc)
-

**Comment by RaverJay** [comment]
image
added:
- run info
- colors
- handles failed assemblies and other missing data

**Comment by hoelzer** [comment]
very nice! Can we somehow also include information about the coverage? This is always an important metric to look at as well. You already have the single coverage plots per reconstructed genome but maybe we can have a kind of coverage matrix plot in the report? Or we could hijack https://github.com/RaverJay/plotCoverageExons.py :)

**Comment by replikation** [comment]
* @hoelzer while i generally agree with coverage it is kind of pointless or less informative for an amplification-based approach as we would need to report every "region coverage" - this is also why we have the coverage plots. at least my take on it. i would favor more a plot featuring all samples in one figure (maybe you mean this with the coverage python script?)

**Comment by RaverJay** [comment]
@hoelzer https://github.com/RaverJay/fastcov is the new plotCoverageExons ;)
Could make one plot for all samples with it

**Comment by hoelzer** [comment]
@RaverJay yeah exactly this is what I meant, cool that there is a new version of plotCoverageExons :D  

@replikation why pointless? I think it's great to see amplicon drop-outs immediately via such plots. I just don't want to go through 24 PDF files so I think @RaverJay s script would be a nice extension. So everything is in one report

**Comment by replikation** [comment]
@hoelzer via plots all in one i agree. i thought you mean values in the table like 20x 100x etc.

**Comment by hoelzer** [comment]
@replikation ah no, I first thought about some values in the table but I agree there is no good way (besides "amplicon-based" coverage values maybe that would become a large table and more complicated). All in one plot would be already sufficient (and maybe that plot can then be also added to the report?)

**Comment by RaverJay** [comment]
image
- added QC pass column
- added coverage plot

thoughts:
- plotting will be ugly and useless if there are many samples

**Pull request merged**
