### PR TITLE
Table style updates

### PR DESCRIPTION
**Pull request by RaverJay**
Trying to improve table readability (implements #207)

image

- Mutations are now toggled, hidden by default
- font size is smaller in main table
- random tweaks to colnames, linebreaks, etc

Play with it here:
[poreCov_summary_report_2022-02-08--15-07-12.zip](https://github.com/replikation/poreCov/files/8024463/poreCov_summary_report_2022-02-08--15-07-12.zip)

### CODE REVIEW

**Comment by RaverJay** [comment]
> how does the table decide if it's showing mutations or not?. E.g. barcode 18 shows some barcode 16 not

> * Mutations are now toggled, hidden by default

I just opened one to show how it looks

**Comment by RaverJay** [comment]
Agreed


concerning doing the same for the other columns:

It would require more JS magic than I know to do the expand/collapse all buttons column-wise - but it would be easy to make them switch the whole table at once - is that good enough?

**Comment by replikation** [comment]
i think the whole table doing expand collapse would also be fine. because we just need A) a table (collapsed) so people can quickly go through to check what variant QC etc. and then B) if more details are needed they can expand. so we don't need to overengineer it.

**Comment by RaverJay** [comment]
Nevermind, I got it done :)

image

**Comment by hoelzer** [comment]
fancy! : )

**Comment by replikation** [comment]
niceeee

**Pull request merged**
