### PR TITLE
Include unclassified in kraken2 stats

### LINKED ISSUE #71: Adjust percentage of classified reads
Currently, the report shows e.g. 100% SARS-CoV-2 and 0% human even if there are only 10 reads classified as SARS-CoV-2 (and the rest is unclassified). 

Thus, it is good to have the absolute numbers now as well but would it not be better to report the percentages in accordance with the Krona plot? E.g. 4 % SARS-Cov-2 if there is 96 % unclassified?

### PR DESCRIPTION
**Pull request by RaverJay**
fixes #71 

suggestions for the color thresholds? right now it is:

%SARS-CoV-2
- \>=95 green
- \>=90 yellow
- \<90 red

%human
- \<=1 green
- \<=5 yellow
- \>5 red

### CODE REVIEW

**Review by replikation — APPROVED** [review]

**Comment by replikation** [comment]
* cool thanks that was quick

**Comment by hoelzer** [comment]
@RaverJay great thx! I think the color coding is good. 

One thing that comes to mind: should we also show _unclassified_? Otherwise the user might think: "okay, I have 70% SC2 and 5% human but what's the rest?" 

I don't want to blow up the report table... but this would make it clear that we only classify vs. a database composed of SC2 and human?

**Comment by RaverJay** [comment]
Would be good, but the table is getting full, yep

I'll experiment with some formatting tweaks and try to add it in
Maybe forcing linebreaks in long sample names helps, etc

**Comment by RaverJay** [comment]
Column is in, will make new branch for style tweaks

**Pull request merged**
