### PR TITLE
Report style tweaks

### PR DESCRIPTION
**Pull request by RaverJay**
- added prominent first line that tells you if all samples passed QC
- shorter column names
- forced linebreaks when fields contain multiple items
- added minimap and fastcov versions
-----------
image

-----------
image

### CODE REVIEW

**Comment by hoelzer** [comment]
great!

One thing: often a negative control is included in a run and that sample should fail QC. Thus, the report will show a somewhat alarming "At least one sample failed QC" even if it is just the negative control. 

But: not sure how to prevent this... I dont see a good way instead of forcing users to name their negative control in a certain way. 

So just see this as a comment that dont needs any action (instead you guys have a good idea)

**Comment by RaverJay** [comment]
Only thing I can think of is checking if the samplename contains 'control' or something

Then I could add a special case when only the control samples failed

**Comment by hoelzer** [comment]
> 
> 
> Only thing I can think of is checking if the samplename contains 'control' or something
> 
> Then I could add a special 'all good' case when only the control samples failed

yeah, that would be a simple way to catch some cases. Maybe check for {negative, control}. And you could add as a disclaimer: "Please check in detail control samples if they were part of your run."

**Comment by RaverJay** [comment]
Yup will need solid explanation

I'll add this

**Comment by replikation** [comment]
maybe something like:

6/18 samples passed QC
1/1 control(s) had zero SARS reads  - or switch to "control not detected"

**Comment by hoelzer** [comment]
> 
> 
> maybe something like:
> 
> 6/18 samples passed QC
> 1/1 control(s) had zero SARS reads - or switch to "control not detected"

ah y, this is also a good idea. A short summary and an indication of "control not automatically detected" if it is not possible by easy string matching

**Comment by RaverJay** [comment]
Nice, on it

**Comment by RaverJay** [comment]
- added sample QC summary
- with info about controls
- controls are marked in table
-------
image
-------
image

**Comment by hoelzer** [comment]
uhhh, advanced, cool @RaverJay

**Review by replikation — APPROVED** [review]

**Pull request merged**
