### PR TITLE
Report VOCs, VOIs etc

### PR DESCRIPTION
**Pull request by RaverJay**
Implements #190 

- always downloads a fresh copy of https://github.com/3dgiordano/SARS-CoV-2-Variants/blob/main/data/variants.csv (is also published)
- uses that to find variant types from pangolin lineage
- adds info to the lineage column if it is something special
- VOCs, VOIs are red, everything else is yellow

image

I want to add a warning if the table could not be loaded somehow, but do not want to it to fail completely in that case

### CODE REVIEW

**Comment by hoelzer** [comment]
When we add the table as a fork is it then updated all the time? Some holds for the submodule... Or: let's make a container for this that has the table included. And a GitHub action could update the container when there is a update of the table? Maybe a bit overhead though ^^

Constellations were added in the early days of omicron I think - here pangolin assigned B.1 or so but the Scorpio (based on constellation) found omicron. It was a bit of a special case. So far, constellations come in handy  when new VOCs pop up and not enough sequences are on GISAID to train a proper pangoLEARN model. So a sequence gets whatever false positive assignment from pangolin but if a constellation file (basically a set of characteristic mutations) is available this can solve the (new) lineage still correctly.

So it's a column mainly informative when new VOCs appear ;)

**Comment by MarieLataretu** [comment]
> The problem seems to be that Nextflow starts a Singularity container with a certain prox setup and then any downloads are blocked on our HPC (slurm).

This can be solved by adding the proxy environment variables to singularity with `singularity.envWhitelist`. Maybe `http_proxy` and `https_proxy` are default environment variables and need to be set on every cluster? Then we could add that to the `nextflow.config`.

**Comment by MarieLataretu** [comment]
> @MarieLataretu yes, if we can add this to the config as a default without impacting e.g. local executions this would be best.

Will open a PR in the next days :ok_hand:

**Comment by replikation** [comment]
@RaverJay can you add the table to the poreCov/data section in a new dir with a readme where its from? So if the automatic download of the table failes it uses the file in poreCov/data/voc-voi   instead?

**Comment by replikation** [comment]
* scratched submodule idea as its another 100MB of data on each git pull with over 5000 files

**Comment by RaverJay** [comment]
image

**Pull request merged**
