### PR TITLE
Update medaka in artic

### PR DESCRIPTION
**Pull request by hoelzer**
Solves #247 

WIP - tests need to be run.

### CODE REVIEW

**Comment by hoelzer** [comment]
```bash
nextflow run replikation/poreCov -r update-medaka-in-artic -profile slurm,singularity --krakendb /scratch/projekte/MF1_SC2/common/databases/kraken2/GRCh38.p13_SC2_2022-03-01.tar.gz --cachedir /singularity/user/mf1/poreCov --update --fastq_pass fastq_pass --samples 230216_GI2-5_Run23-043_samplesheet.csv --primerV V4.1 --medaka_model r941_min_hac_g507 -resume
```

```bash
[87/93c492] process > artic_ncov_wf:artic_medaka (17)                      [100%] 24 of 24 ✔
```

🤯

**Comment by hoelzer** [comment]
Works for me also w/ `--medaka_model r1041_e82_400bps_sup_g615`

Unfortunately, I can not test this branch w/ `--primerV V5.3.2_400` - can I somehow merge that in here @replikation @DataSpott ? 

Then we could compare here the results between

1) `--primerV V5.3.2_400` w/ old ARTIC container and medaka old model
2) `--primerV V5.3.2_400` w/ new ARTIC container and medaka model `r1041_e82_400bps_sup_g615`

**Comment by hoelzer** [comment]
I injected the matching primer scheme via 

`--primerV poreCov/data/external_primer_schemes/nCoV-2019/V5.3.2_400/nCoV-2019.primer.bed`

and it looks really good. 

I get, from a birds eye view, the same mutations as with the old ARTIC container but we're using now medaka 1.7.2 and have access to the new R1041 etc.. models. 

So comparing R9 model and now R10 w/ new container via md5 checksums of the final genome FASTAS I only see differences for four samples in this run. For one, the new model repaired a frame shift - perfect. For the other three we will look via pairwise whole genome aln and then report here

**Comment by hoelzer** [comment]
These are the only differences we discovered so far. Quite minor in my eyes. And bc/ we basecalled this run w/ R10.4.1* model, it makes also fully sense to me to use that model in Medaka. Even though there are slight differences that "look better" with an older model such as R9. However, basecalling w/ R10 model and then analyses with R9 model is also not really justifiable.

**Review by replikation — APPROVED** [review]

**Comment by replikation** [comment]
@DataSpott if everything is fine on your end we can merge

**Comment by DataSpott** [comment]
Tested it with one of our routine runs (starting from fastq-pass) and could only find in one sample a difference. this was only one more ambiguous base with the old container compared to the new container (1112 vs 1113 ambiguous bases). So on my end the run worked fine.
Tested with commit "db05fa8".

**Pull request merged**
