### PR TITLE
auto get latest pangolin container -> release 0.8.0

### PR DESCRIPTION
**Pull request by replikation**
* auto gets the latest "auto build" pangolin container
* @RaverJay we need some super slight adjustments to the summary report for "version reporting" on pangolin and pangolearn
* the pangolin version can be directly accessed via `params.pangolindocker`
* the "style" of the docker is `nanozoo/pangolin:2.3.8--2021-04-21`
    * `nanozoo/pangolin:<pangolinversion>--<pangoLEARNversion>`
    * we need both versions on the final report

### CODE REVIEW

**Comment by replikation** [comment]
perfect thx. @hoelzer and me will test on this PR at least until one or two "auto-updates" happened before merging

**Comment by hoelzer** [comment]
I just tried running this branch, but got an error in the reporting step:

```
[fd/0d632a] process > create_summary_report_wf:summary_report (1) [100%] 1 of 1, failed: 1 ✘
Error executing process > 'create_summary_report_wf:summary_report (1)'

Caused by:
  Process `create_summary_report_wf:summary_report (1)` terminated with an error exit status (2)

Command executed:

  echo 'sample,num_unclassified,num_sarscov2,num_human' > kraken2_results.csv
  for KF in IMSSC2-502-2021-00055.kreport IMSSC2-71-2021-00094.kreport IMSSC2-71-2021-00091.kreport IMSSC2-75-2021-00054.kreport IMSSC2-4-2021-04085.kreport IMSSC2-502-2021-00052.kreport IMSSC2-502-2021-00054.kreport IMSSC2-71-2021-00092.kreport IMSSC2-71-2021-00095.kreport IMSSC2-71-2021-00096.kreport IMSSC2-75-2021-00051.kreport negative-controlTE-01.kreport IMSSC2-4-2021-04081.kreport IMSSC2-502-2021-00051.kreport IMSSC2-75-2021-00055.kreport IMSSC2-502-2021-00053.kreport IMSSC2-4-2021-04060.kreport IMSSC2-4-2021-04101.kreport IMSSC2-75-2021-00052.kreport IMSSC2-4-2021-04096.kreport IMSSC2-75-2021-00053.kreport; do
  NUNCLASS=$(awk -v ORS= '$5=="0" {print $3}' $KF)
  NSARS=$(awk -v ORS= '$5=="2697049" {print $3}' $KF)
  NHUM=$(awk '$5=="9606" {print $3}' $KF)
  echo "${KF%.kreport},${NUNCLASS:-0},${NSARS:-0},${NHUM:-0}" >> kraken2_results.csv
  done

  summary_report.py             -v container.config             --porecov_version auto_pangolin:a41f8d4e48510aac36cddd8592a28fad8b520ac7:afa76a8577f9adcb98207e48762a6fce             --primer V3             -p pangolin_results.csv             -q president_results.tsv             -n nextclade_results.tsv             -k kraken2_results.csv             -c $(echo coverages_IMSSC2-75-2021-00054.bam_IMSSC2-75-2021-00055.bam_negative-controlTE-01.bam.png coverages_IMSSC2-71-2021-00094.bam_IMSSC2-71-2021-00095.bam_IMSSC2-71-2021-00096.bam_IMSSC2-75-2021-00051.bam_IMSSC2-75-2021-00052.bam_IMSSC2-75-2021-00053.bam.png coverages_IMSSC2-502-2021-00052.bam_IMSSC2-502-2021-00053.bam_IMSSC2-502-2021-00054.bam_IMSSC2-502-2021-00055.bam_IMSSC2-71-2021-00091.bam_IMSSC2-71-2021-00092.bam.png coverages_IMSSC2-4-2021-04060.bam_IMSSC2-4-2021-04081.bam_IMSSC2-4-2021-04085.bam_IMSSC2-4-2021-04096.bam_IMSSC2-4-2021-04101.bam_IMSSC2-502-2021-00051.bam.png | tr ' ' ',')             -s samples_list.csv

Command exit status:
  2

Command output:
  (empty)

Command error:
  LOG: Started summary_report.py ...
  usage: summary_report.py [-h] -v VERSION_CONFIG --porecov_version
                           PORECOV_VERSION --pangolin_docker PANGOLIN_DOCKER
                           [--primer PRIMER] [-p PANGOLIN_RESULTS]
                           [-n NEXTCLADE_RESULTS] [-q PRESIDENT_RESULTS]
                           [-k KRAKEN2_RESULTS] [-c COVERAGE_PLOTS] [-s SAMPLES]
  summary_report.py: error: the following arguments are required: --pangolin_docker
```

**Comment by replikation** [comment]
@hoelzer was missing one input for one of the summary report cases. should be fixed

**Comment by RaverJay** [comment]
fixed a typo

**Comment by hoelzer** [comment]
Thanks, was running through now after the fix using container:nanozoo/pangolin:2.3.8--2021-04-21

**Review by replikation — COMMENTED** [review]
* code looks conflict free now

**Comment by replikation** [comment]
* so far all scheduled container were build sucessfully

**Comment by RaverJay** [comment]
One thought I just had:

For the special case of in-field sequencing & analysis it might be good to not force such automatic updates that include container downloads, as your internet connection might not support it.

We should retain the possibility of 'installing' poreCov by running the fast5 test profile once, and then having it set up on that version for continued use

**Comment by replikation** [comment]
@RaverJay if no internet connection is available it defaults to the "hardcoded" pangolin option.

**Comment by replikation** [comment]
* but yes i should ensure that the "hardcoded" docker version is at some point installed during a first run

**Comment by RaverJay** [comment]
> @RaverJay if no internet connection is available it defaults to the "hardcoded" pangolin option.

That's great. Still want to avoid the case where there is some very bad connection and you get stuck in a download with 0.4 kbps or something :sweat_smile:

**Comment by replikation** [comment]
@RaverJay okay poreCov is now automatically installing/using the "failsafe pangolin" if the workflow profile contains local, additionally, I added the "--no_auto" flag to completely deactivate the whole auto pangolin story
* also the `--rki` flag is now removed and therefore "default on"

**Comment by replikation** [comment]
* everything alright on my end @hoelzer

**Comment by hoelzer** [comment]
@replikation also run through w/o errors on my end

**Pull request merged**
