### PR TITLE
added `nextclade_percentN_spike` column to datatables

### PR DESCRIPTION
**Pull request by MarieLataretu**
- based on nextclade `missing` output
- empty if nextclade output empty
- HTML report untouched

### CODE REVIEW

**Review by replikation — APPROVED** [review]

**Comment by replikation** [comment]
testrun fine?

**Comment by MarieLataretu** [comment]
I successfully run it on a routine run; let me check the test profiles, too!

**Comment by MarieLataretu** [comment]
all test profiles are fine 🚀

**Comment by replikation** [comment]
perfect then ill merge it thanks :)

**Pull request merged**
