### PR TITLE
nanopolish wo basecalling, improv errorhandling

### LINKED ISSUE #94: Provide `--fastq_pass` AND `--fast5` to`--nanopolish`
Hi, me again. Thanks for your updates! 

I have a request, I hope it make sense to you. Would it be possible to provide both fast5 and fastq to the nanopolish workflow, but avoid basecalling? I basecalled the fast5 in a different platform from where I'm launching poreCov, so I have both types of files already. I have gpu in the former but no in the latter. 

I notice that if I provide fast5, then poreCov asumes it has to basecall them, am I right? May be providing both could avoid the basecalling step and go directly to nanopolish. 

If you think it makes sense but don't have the time, I could try to implement it and fill a PR. Let me know!

### PR DESCRIPTION
**Pull request by replikation**
* closes #94
   * sequencing summary is provided via `--nanopolish` and it is only necessary if `--fastq` or `--fastq_pass` is provided
* did some small test runs and works fine
* added more verbose error codes throughout the workflow
* needs some proper testing to validate if all workflows are chosen correctly
* @iferres would be glad if you could do some testing

```bash
# update poreCov
nextflow pull replikation/poreCov
# example run (please add profile etc.)
nextflow run replikation/poreCov  -r no_basecall_nanopolish --fast5 fast5_dir/ --fastq_pass fastq_pass/ --nanopolish sequencing_summary.txt 
```

### CODE REVIEW

**Comment by iferres** [comment]
Hi, thanks so much @replikation !! Apparently, it ran fine over real samples. My colleagues are the ones with the samples and doing the analyses so I asked them to check if everything was ok, but we are on a holiday these days so I will probably have to wait until monday to make sure it is, sorry.

PS. We had a problem with some deletions we expected but weren't there. We suspected of medaka, so it will probably be solved with this PR and nanopolish. If it isn't the case, I will fill a new issue reporting that.

**Comment by replikation** [comment]
if inDels are missing and not reported it should be an issue with artic assembly itself, if its "parameter tweakable" it could be resolved on my end otherwise the issue has to go to "https://github.com/artic-network/fieldbioinformatics" but yes report an issue and i can also investigate. thanks for the response.

okay testing on our end was also fine. so ill merge and when you can also confirm that everything is okay ill do a new poreCov release for everyone.

**Comment by hoelzer** [comment]
@iferres 

> PS. We had a problem with some deletions we expected but weren't there. We suspected of medaka, so it will probably be solved with this PR and nanopolish. If it isn't the case, I will fill a new issue reporting that.

Actually, that could be really interesting and important if you can report about this (either at ARTIC directly, as @replikation suggested, or also here). We experienced also problems with deletions in an Illumina protocol where the deletions are located close to the ends of the amplicons (and can be soft-clipped, ...). Could be also that this is some issue with Nanopore and specific ARTIC amplicons? Missing deletions in important regions can easily lead to misclassification of the lineage - so might be important what you and your colleagues discovered! Thanks & happy eastern ;)

**Comment by iferres** [comment]
We think it's something with poreCov parameters as we are still having that problem with the nanopolish runs. We aren't experiencing that issue with the [Connor's Lab](https://github.com/connor-lab/ncov2019-artic-nf) implementation. Still working on that. I asked my colleague to write what is she noticing to report you guys as detailed as possible. We could even send you a fastq sample to check it if you want. Just give us some time since we are in a hurry with on-going sequencing projects, and also these fake holidays :P

**Comment by replikation** [comment]
* okay thats strange, the biggest difference i see is that they set "normalize" during assembly to 500, ill open e saparate branch so we can test some parameters

**Pull request merged**
