### PR TITLE
added skip-scorpio parameter fixes #234

### LINKED ISSUE #234: add skip scorpio parameter to pangolin
From `pangolin` version 4 on the linage assignment is done by Usher. However `scorpio` overwrites the results which leads to a lot unassigned samples.

I'll add a parameter to skip `scorpio` in the `pangolin` run

### PR DESCRIPTION
**Pull request by MarieLataretu**
- for now the default is that `scorpio` is not skipped and can be skipped with `pangolin_skip_scorpio`

### CODE REVIEW

**Comment by hoelzer** [comment]
> what is the rationale behind it?

This is a pangolin issue currently discussed in the community. The problem is that `scorpio` overwrites correct PangoLearn/Usher assignments. For example this happens for recombinants bc/ there are yet no (?) `scorpio` constellation files for recombinants. But this also happens for BA.4/5 which is even worse. E.g. see discussions here:

https://github.com/cov-lineages/pango-designation/issues/599
https://github.com/cov-lineages/pango-designation/issues/713
https://github.com/cov-lineages/pango-designation/issues/645
https://github.com/cov-lineages/pango-designation/issues/603
...

We performed some in-house tests annotation the full DESH collection w/ and w/o `scorpio` and the results w/o `scorpio` look more stable and accurate. That's why we want to add a parameter to deactivate `scorpio` and thus the overwrite of previous pangoLearn/User assignments. 

There is also a not yet merged PR (https://github.com/cov-lineages/pangolin/pull/461) about that topic. So maybe the way `scorpio` works will be changed anyway in the (near) future. But for now, it would be good to have an option to deactivate it.

**Comment by hoelzer** [comment]
@MarieLataretu but would it be not better to have a general `--additional_pango_params` ? In case also other options should be given to pangolin in the future

**Comment by MarieLataretu** [comment]
> @MarieLataretu but would it be not better to have a general `--additional_pango_params` ? In case also other options should be given to pangolin in the future...
> 
> EDIT: although checking the way you implemented it now is also nice. It's more explicit to have a parameter for deactivation directly in the help

Yes, it's more explicit and if `--additional_pango_params` is per default `--skip-scorpio` it's kind of hard to turn it off on the command line. 

Of course `--additional_pango_params` would be more flexible.

**Comment by MarieLataretu** [comment]
I wasn't sure about changing the default behavior - I can change that to skip `scorpio` per default, if you agree

**Comment by hoelzer** [comment]
Yeah, that's the question. We could also deactivate it by default and write that in the release notes (citing also the discussions I mentioned here)? Could be just that when the Pango devs change also the default behavior in the tool itself we also might have to change that back. 

Assuming that many people just use the pipeline and report the results it might be even good we make this decision based on the current discussions and tests. So from my site also +1 to make this the current default

**Comment by replikation** [comment]
i mean most users are probably not reading this so i would just set the defaults to the best practice. :)

**Comment by MarieLataretu** [comment]
I changed the default to `true`.
Skipping scorpio can be deactivated with `--pangolin_skip_scorpio false`

**Comment by hoelzer** [comment]
@replikation yeah, I like that it's not so DoppeltGemoppelt

btw the current release vs/ Maries master branch w/ scorpio deactivated: 
https://twitter.com/martinhoelzer/status/1537769594546442241

**Comment by MarieLataretu** [comment]
Done.
Per default is `--scorpio`  `false`, so `--skip-scorpio` is added to pangolin.

**Comment by replikation** [comment]
Perfect. I'll run some tests and then merge. Thank you

**Pull request merged**
