### PR TITLE
Dev replikation

### PR DESCRIPTION
**Pull request by replikation**
* living PR on code rewrite and test profiles

### CODE REVIEW

**Comment by hoelzer** [comment]
@working guppy CPU #20 I can test this if you want (do we have some test fast5 somewhere, OSF?)

**Comment by replikation** [comment]
-profile test_fast5 @hoelzer see help fastq fasta and fast5 can be "auto supplied" for testing

**Comment by hoelzer** [comment]
> -profile test_fast5 @hoelzer see help fastq fasta and fast5 can be "auto supplied" for testing

ah, awesome! I will test! 

btw you switched to V1200 primer set as the default now? (its fine, just to know because e.g. P3 uses V3 currently)

**Comment by replikation** [comment]
V3 should be default; its only set to V1200 for the test fastq set (as i only had a good and small in V1200)

**Comment by hoelzer** [comment]
> V3 should be the default; its only set to V1200 for the test fastq set (as i only had a good and small one for V1200)

ah, I see. great!

**Comment by replikation** [comment]
* @hoelzer i would merge now

**Comment by hoelzer** [comment]
@replikation looks good! 

* I just updated president
* and I switched from `baseName` to `simpleName` for fastq input because otherwise I ended up with something like `FAO96286_barcode07.fastq_seq_ident_check.tsv` because `baseName` did not remove the `.fastq` from a `.fastq.gz` file

**Review by hoelzer — APPROVED** [review]

**Pull request merged**
